version: 1.0.{build}
skip_tags: true

branches:
  only:
    - master

image: Visual Studio 2017

build_script:
  - cmd: 'cd %APPVEYOR_BUILD_FOLDER%\build && cmake ..'
  - cmd: 'msbuild %APPVEYOR_BUILD_FOLDER%\build\bfxr.sln'

platform:
  - x86
  - x64

