version: 1.0.{build}
skip_tags: true

branches:
  only:
    - master

image: Visual Studio 2017

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmd: '%APPVEYOR_BUILD_FOLDER%\tool.py gitfix %APPVEYOR_BUILD_FOLDER%'
  - git submodule update --init --recursive

build_script:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\tool.py download https://www.libsdl.org/release/SDL2-devel-2.0.9-VC.zip %APPVEYOR_BUILD_FOLDER%\sdl2.zip'
  - cmd: '%APPVEYOR_BUILD_FOLDER%\tool.py unzip %APPVEYOR_BUILD_FOLDER%\sdl2.zip %APPVEYOR_BUILD_FOLDER%\sdl2'
  - cmd: 'mkdir %APPVEYOR_BUILD_FOLDER%\build'
  - cmd: 'mkdir %APPVEYOR_BUILD_FOLDER%\deploy'
  - cmd: 'cd %APPVEYOR_BUILD_FOLDER%\build && cmake -D CMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%/deploy/ SDL2_HINT_ROOT=%APPVEYOR_BUILD_FOLDER%\sdl2\SDL2-2.0.9\ ..'
  - cmd: 'cmake --build %APPVEYOR_BUILD_FOLDER%\build --config Release --target install'

platform:
  - x86

after_build:
  - cmd: '7z a %APPVEYOR_BUILD_FOLDER%\deploy\artifact.zip %APPVEYOR_BUILD_FOLDER%\deploy\*'

artifacts:
  - path: deploy\artifact.zip

deploy:
  - provider: BinTray
    username: madeso
    api_key:
      # api key from https://bintray.com/profile/edit
      # encrypted in https://ci.appveyor.com/tools/encrypt
      secure: 4+yuIks0NBwT5o8cMeC0uc2qRFlG8y3rhyRtalbby0wwlCTBlquzVQqQSVdm2a1J
    subject: madeso
    repo: bfxr-generic
    package: bfxr-master
    version: master
    publish: true
    override: true
    explode: true
