version: 1.0.{build}
skip_tags: true

branches:
  only:
    - master

image: Visual Studio 2017

build_script:
  - ps: (new-object net.webclient).DownloadFile('https://www.libsdl.org/release/SDL2-devel-2.0.9-VC.zip', '%APPVEYOR_BUILD_FOLDER%\sdl2.zip')
  - ps: Expand-Archive %APPVEYOR_BUILD_FOLDER%\sdl2.zip -DestinationPath %APPVEYOR_BUILD_FOLDER%\sdl2
  - cmd: 'mkdir %APPVEYOR_BUILD_FOLDER%\build'
  - cmd: 'cd %APPVEYOR_BUILD_FOLDER%\build && cmake -d SDL_HINT_PATH=%APPVEYOR_BUILD_FOLDER%\sdl2 ..'
  - cmd: 'msbuild %APPVEYOR_BUILD_FOLDER%\build\bfxr.sln'

platform:
  - x86
  - x64

