version: 1.0.{build}
skip_tags: true

branches:
  only:
    - master

image: Visual Studio 2017

build_script:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\tool.py download https://www.libsdl.org/release/SDL2-devel-2.0.9-VC.zip %APPVEYOR_BUILD_FOLDER%\sdl2.zip'
  - cmd: '%APPVEYOR_BUILD_FOLDER%\tool.py unzip %APPVEYOR_BUILD_FOLDER%\sdl2.zip %APPVEYOR_BUILD_FOLDER%\sdl2'
  - cmd: 'mkdir %APPVEYOR_BUILD_FOLDER%\build'
  - cmd: 'cd %APPVEYOR_BUILD_FOLDER%\build && cmake -D SDL2_HINT_ROOT=%APPVEYOR_BUILD_FOLDER%\sdl2\SDL2-2.0.9\ ..'
  - cmd: 'msbuild %APPVEYOR_BUILD_FOLDER%\build\bfxr.sln'

platform:
  - x86

